@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@path = http://{{host}}/api/

GET {{path}}terminals
###
GET {{path}}terminal/7551040072
###
POST {{path}}terminal
content-type: application/json

{
  "number": "1010",
  "imei": "123456789123456",
  "phoneNumber": "05061698"
}
###
PUT {{path}}terminal/1010
content-type: application/json

{
  "latitude": 65.0,
  "longitude": 25.0,
  "speed": 10.2
}
###
DELETE {{path}}terminal/1010
