GET http://superapp1.superapp.fi:3000/api/
###
GET http://superapp1.superapp.fi:3000/api/7551040072
###
POST http://localhost:3000/api/
content-type: application/json

{
  "number": "1010",
  "imei": "123456789123456",
  "phoneNumber": "05061698"
}
###
PUT http://localhost:3000/api/1010
content-type: application/json

{
  "latitude": 65.0,
  "longitude": 25.0,
  "speed": 10.2
}
###
DELETE http://localhost:3000/api/1010
